### ISSUE TITLE
我从1.4.2更新到1.14.0，并且使用了文件夹包含几个service一起,急需大神指教。

### ISSUE THREAD

**Issue by whyour** [whxaxes/egg-ts-helper#20]
```
> egg-bin dev -r 'egg-ts-helper/register'

2018-11-22 17:46:28,246 INFO 82507 [master] node version v8.12.0
2018-11-22 17:46:28,247 INFO 82507 [master] egg version 2.11.2
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/app/controller/index.d.ts created
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/app/middleware/index.d.ts created
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/app/model/index.d.ts created
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/config/index.d.ts created
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/config/plugin.d.ts created
[egg-ts-helper] /Users/wangpeng/resp/wt-hulk/back-end/typings/app/service/index.d.ts created
2018-11-22 17:46:29,422 INFO 82507 [master] agent_worker#1:82509 started (1171ms)

/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: [egg-core] load file: /Users/wangpeng/resp/wt-hulk/back-end/app/service/TeamService.ts, error: [egg-core] load file: /Users/wangpeng/resp/wt-hulk/back-end/app/service/activityService.ts, error: ⨯ Unable to compile TypeScript:
app/service/activityService.ts(6,22): error TS2348: Value of type 'Model<any>' is not callable. Did you mean to include 'new'?

    at createTSError (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.loadFile (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/egg-core/lib/utils/index.js:19:19)
    at getExports (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/egg-core/lib/loader/file_loader.js:199:23)
    at ContextLoader.parse (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at ContextLoader.load (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToContext (/Users/wangpeng/resp/wt-hulk/back-end/node_modules/egg-core/lib/loader/egg_loader.js:407:28)
[2018-11-22 17:46:33.457] [cfork:master:82507] worker:82516 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-11-22 17:46:33.457] [cfork:master:82507] don't fork, because worker:82516 will be kill soon
2018-11-22 17:46:33,457 INFO 82507 [master] app_worker#1:82516 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-11-22 17:46:33.458] [cfork:master:82507] worker:82516 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
```

```
// typings

declare module 'egg' {
  interface IModel {
    Console: {
      CrmImportRecord: ReturnType<typeof ConsoleCrmImportRecord>;
    };
    Lesschat: {
      CrmContact: ReturnType<typeof LesschatCrmContact>;
      CrmCustomer: ReturnType<typeof LesschatCrmCustomer>;
      Department: ReturnType<typeof LesschatDepartment>;
      Tag: ReturnType<typeof LesschatTag>;
      Team: ReturnType<typeof LesschatTeam>;
      User: ReturnType<typeof LesschatUser>;
    };
  }
}
```

**Comment by whxaxes** [comment]
```
TSError: [egg-core] load file: /Users/wangpeng/resp/wt-hulk/back-end/app/service/TeamService.ts, error: [egg-core] load file: /Users/wangpeng/resp/wt-hulk/back-end/app/service/activityService.ts, error: ⨯ Unable to compile TypeScript:
app/service/activityService.ts(6,22
```

这个文件代码能发出来看看么

**Comment by whyour** [comment]
```
import { Service } from 'egg';
export default class ActivityService extends Service {
  public async addActivity(obj: any) {
    const { ctx } = this;
    const data = await ctx.model.Activity(obj).save();
    return data;
  }
  public async getActivties(condition: any, fields: any) {
    const { ctx } = this;
    const data = await ctx.model.Activity.find(condition, fields).lean();
    return data;
  }
}

```


egg test  里面  用的
```
const data = await new ctx.model.Activity(obj).save();
```

最终结果还是没法在一个文件夹下面挂载多个service或者model或者其他层。

**Comment by whxaxes** [comment]
没懂你的意思，能提供个稳定复现的 repo 么？我可以帮你看看

**Comment by whyour** [comment]
@whxaxes  
```
export default (app) => {
    const mongoose = app.mongoose;
    const Schema = mongoose.Schema;
    const conn = app.mongooseDB.get('lcMongodbServer');
    const CrmContactSchema = new Schema({
        mobile: { type: String },
        team: { type: Schema.Types.ObjectId },
        customer: { type: Schema.Types.ObjectId },
        is_deleted: { type: Number }
    });
    return conn.model('crm_contacts', CrmContactSchema);
}

```

**Comment by whyour** [comment]
好了，加了

还有一个办法，将 egg-ts-helper 升到 1.10.0 ，在 typings/index.d.ts 中添加这么一个声明来复写掉 model 的类型
```
import { MongooseModels } from 'egg';

declare module 'egg' {
  interface IModel extends MongooseModels {}

  // extend app
  interface Application {
    model: IModel;
  }

  // extend context
  interface Context {
    model: IModel;
  }
}
```

还有个问题，每次启动都会覆盖typings下的文件吗。

**Comment by whxaxes** [comment]
@whyour  会覆盖 app/ 和 config/ 下的，如果你不想被覆盖，就写到 typings/ 下

**Comment by whxaxes** [comment]
@whyour  你的问题不是 egg-ts-helper 带来的，是 https://github.com/eggjs/egg-mongoose/blob/master/index.d.ts  里的声明有问题 ...

**Comment by whxaxes** [comment]
egg-ts-helper 生成的 model 下的声明，都是挂载到 `IModel` 下的，这个由你们决定要不要挂到 `context` 这些之下，因为 model 的实现太多了，没法通配，只能由你们来决定了

**Comment by whxaxes** [comment]
没其他问题我就 close 掉了
